FROM golang:1.21 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/server

# Final stage: create a minimal image for the Go application
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/main .
COPY --from=builder /app/config_test.json /root/config_test.json

# Expose the application port
EXPOSE 8088

# Command to run the Go application
CMD ["./main", "-config=config_test.json"]
