version: "2"

run:
  timeout: 5m
  tests: true

output:
  formats:
    text:
      path: stdout
  sort-results: false

# See: https://golangci-lint.run/usage/linters/
linters:
  enable:
    - bodyclose
    - errcheck
    - ineffassign
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gosec
    - staticcheck
    - nilerr
    - nlreturn
    - predeclared
    - revive
    - rowserrcheck
    - unconvert
    - wastedassign
  settings:
    gocritic:
      enabled-checks:
        - sloppyReassign
        - nestingReduce
        - httpNoBody
        - badLock
        - paramTypeCombine
        - equalFold
        - appendCombine
        - nilValReturn
        - weakCond
    nlreturn:
      block-size: 2
    forbidigo:
      forbid:
        - pattern: '^print.*$'
        - pattern: 'fmt\.Print.*'
        - pattern: 'ioutil\.*'
    funlen:
      lines: 120
    gosec:
      excludes:
        - G101

formatters:
  enable:
    - gofumpt