name: run-tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: pass12
          MYSQL_DATABASE: dhapi_test
          MYSQL_USER: dev
          MYSQL_PASSWORD: pass12
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Wait for MySQL to be ready
        run: |
          until docker exec -it $(docker ps -qf "ancestor=mysql:8.0") mysqladmin ping --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Debug environment variables
        run: printenv | sort

      - name: Run database migrations
        run: go run cmd/migrate/migrate.go -action up -config config_test.json
        env:
          DB_HOST: mysql
          DB_USER: dev
          DB_PASSWORD: pass12
          DB_NAME: dhapi_test

      - name: Run Go tests
        run: go test ./...
        env:
          DB_HOST: mysql
          DB_USER: dev
          DB_PASSWORD: pass12
          DB_NAME: dhapi_test

      - name: Stop Docker containers
        run: docker stop $(docker ps -q)
