name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: pass12
          MYSQL_DATABASE: dhapi_test
          MYSQL_USER: dev
          MYSQL_PASSWORD: pass12
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Wait for MySQL to be ready
        run: |
          until docker exec -it $(docker ps -qf "ancestor=mysql:8.0") mysqladmin ping --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run database migrations
        run: go run cmd/migrate/migrate.go -action up

      - name: Build and start Go application
        run: |
          docker build -t my-go-app .
          docker run -d -e DB_HOST=127.0.0.1 -e DB_USER=dev -e DB_PASSWORD=pass12 -e DB_NAME=dhapi_test --network host my-go-app

      - name: Run Go tests
        run: go test ./...

      - name: Stop Docker containers
        run: docker stop $(docker ps -q)
